# References {.unnumbered}

::: {#refs}
:::

**Authorship statement:**I declare that the work in this assessment is my own work and I acknowledge the use of Google NotebookLM (version Standard (free), Google, https://notebooklm.google/) to initial searches, proof reading and grammar correction.

MacLachlan, A. CASA0023 Remotely Sensing Cities and Environments: 1 Getting started with remote sensing. Available at: https://andrewmaclachlan.github.io/CASA0023/intro.html (Accessed: 18 January 2026).

Brady, M. (2021) Remote Sensing for Dummies. Available at: https://storymaps.arcgis.com/stories/cb1577b0f5bc485c974b4ea19d52282d (Accessed: 18 January 2026).

Kerle, N., Janssen, L.L.F. and Huurneman, G.C. (eds.) (2004) Principles of Remote Sensing. 3rd edn. Enschede: International Institute for Geo-Information Science and Earth Observation (ITC).

Kopecká, M., Szatmári, D. and Rosina, K. (2017) ‘Analysis of urban green spaces based on Sentinel-2A: Case studies from Slovakia’, Land, 6(2), p. 25.

Kuc, G. and Chormański, J. (2019) ‘Sentinel-2 imagery for mapping and monitoring imperviousness in urban areas’, The International Archives of the Photogrammetry, Remote Sensing and Spatial Information Sciences, 42, pp. 43–47.

NASA. Spectral Bands and Applications. Available at: https://science.nasa.gov/mission/landsat/spectral-bands-and-applications/ (Accessed: 25 January 2026).

NASA:Landsat 8. Available at: https://science.nasa.gov/mission/landsat-8/ (Accessed: 23 January 2026).

Joseph M. Smith/NASA: Landsat Fire and Thermal Anomaly Data Added to FIRMS. Available at: https://www.earthdata.nasa.gov/news/feature-articles/landsat-fire-thermal-anomaly-data-added-firms (Accessed: 23 January 2026).

NASA: Landsat’s Role in Supporting Urban Planning. Available at https://science.nasa.gov/mission/landsat/benefits/urban-development/ (Accessed: 23 January 2026).

MacLachlan, A. CASA0023 Remotely Sensing Cities and Environments: 3 Corrections. Available at: https://andrewmaclachlan.github.io/CASA0023/3_corrections.html (Accessed: 31 January 2026).

Shimada, M., 2010. Ortho-rectification and slope correction of SAR data using DEM and its accuracy evaluation. IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing, 3(4), pp.657-671.

Vermote, E.F. and Kotchenova, S., 2008. Atmospheric correction for the monitoring of land surfaces. Journal of Geophysical Research: Atmospheres, 113(D23).

National Oceanic and Atmospheric Administration (NOAA), Chemical Sciences Laboratory. Platform: AERONET. Available at: <https://csl.noaa.gov/projects/firex-aq/groundsites/aeronet.html#:~:text=The%20program%20was%20established%20by%20NASA%20and,>*%20Missoula%20*%20Taylor%20Ranch%20\*%20McCall (Accessed 26 March 2026).

MacLachlan, A. CASA0023 Remotely Sensing Cities and Environments: 4 Classification I. Available at: https://andrewmaclachlan.github.io/CASA0023/4_policy.html (Accessed: 22 February 2026).

MacLachlan, A., Biggs, E., Roberts, G. and Boruff, B., 2021. Sustainable city planning: a data-driven approach for mitigating urban heat.Frontiers in Built Environment,6, p.519599.

Prefeitura de Belo Horizonte (2019). Plano Diretor - Lei 11.181/19. Available at: https://prefeitura.pbh.gov.br/politica-urbana/planejamento-urbano/plano-diretor/proposta (Accessed: 22 February 2026).

Secretaria Municipal de Política Urbana da Prefeitura de Belo Horizonte (2020). E-book Plano Diretor de BH: OCUPAÇÃO DO SOLO". Available at: https://prefeitura.pbh.gov.br/sites/default/files/estrutura-de-governo/politica-urbana/2023/001_zoneamento_0.pdf (Accessed: 22 February 2026).

Copernicus Data Space Ecosystem. Sentinel-2. Available at: https://dataspace.copernicus.eu/data-collections/copernicus-sentinel-missions/sentinel-2 (Accessed: 22 February 2026).

MacLachlan, A. CASA0023 Remotely Sensing Cities and Environments: 5 Google Earth Engine I. Available at: https://andrewmaclachlan.github.io/CASA0023/5_GEE_I.html (Accessed: 01 March 2026).

Gorelick, N., Hancher, M., Dixon, M., Ilyushchenko, S., Thau, D., Moore, R., 2017. Google Earth Engine: Planetary-scale geospatial analysis for everyone. Remote Sensing of Environment, Big Remotely Sensed Data: tools, applications and experiences 202, 18–27.

Hansen, M.C., Potapov, P.V., Moore, R., Hancher, M., Turubanova, S.A., Tyukavina, A., Thau, D., Stehman, S.V., Goetz, S.J., Loveland, T.R. and Kommareddy, A., 2013. High-resolution global maps of 21st-century forest cover change. science, 342(6160), pp.850-853.

Lobell, D.B., Thau, D., Seifert, C., Engle, E. and Little, B., 2015. A scalable satellite-based crop yield mapper. Remote Sensing of Environment, 164, pp.324-333.

Ravanelli, R., Nascetti, A., Cirigliano, R.V., Di Rico, C., Leuzzi, G., Monti, P. and Crespi, M., 2018. Monitoring the impact of land cover change on surface urban heat island through Google Earth Engine: Proposal of a global methodology, first applications and problems. Remote Sensing, 10(9), p.1488.

MacLachlan, A. CASA0023 Remotely Sensing Cities and Environments: 6 Classification I. Available at: https://andrewmaclachlan.github.io/CASA0023/6_classification_I.html (Accessed: 06 March 2026).

Jensen, J.R. (2015) Introductory digital image processing: a remote sensing perspective. 4th edn. Glenview, IL: Prentice-Hall Inc.

Sheykhmousa, M., Mahdianpari, M., Ghanbari, H., Mohammadimanesh, F., Ghamisi, P. and Homayouni, S. (2020) ‘Support Vector Machine Versus Random Forest for Remote Sensing Image Classification: A Meta-Analysis and Systematic Review’, IEEE Journal of Selected Topics in Applied Earth Observations and Remote Sensing.

GISGeography (2014) Image Classification Techniques in Remote Sensing. Available at: https://gisgeography.com/image-classification-techniques-remote-sensing/ (Accessed: 06 March 2026).

Barsi, Á., Kugler, Z., László, I., Szabó, G. and Abdulmutalib, H.M. (2018) ‘Accuracy dimensions in remote sensing’, International Archives of the Photogrammetry, Remote Sensing and Spatial Information Sciences.

Pal, M. and Mather, P.M. (2005) ‘Support vector machines for classification in remote sensing’, International Journal of Remote Sensing.

MacLachlan, A. CASA0023 Remotely Sensing Cities and Environments: 7 Classification II. Available at:https://andrewmaclachlan.github.io/CASA0023/7_classification_II.html (Accessed: 20 March 2026).

Dronova, I., 2015. Object-based image analysis in wetland research: A review. Remote Sensing, 7(5), pp.6380-6413.

Reschke, J. and Hüttich, C., 2014. Continuous field mapping of Mediterranean wetlands using sub-pixel spectral signatures and multi-temporal Landsat data. International Journal of Applied Earth Observation and Geoinformation, 28, pp.220-229.

MacLachlan, A. CASA0023 Remotely Sensing Cities and Environments: 9: Synthetic Aperture Radar (SAR) data’. Available at:https://andrewmaclachlan.github.io/CASA0023/9_SAR.html (Accessed: 22 March 2026).

Ballinger, O. Remote Sensing for OSINT: ‘Blast Damage Assessment’. Case Study 10. Available: https://bellingcat.github.io/RS4OSINT/C3_Blast.html (Accessed: 22 March 2026).

Vassileva, M., Al-Halbouni, D., Motagh, M., Walter, T.R., Dahm, T. and Wetzel, H.U. (2021) ‘A decade-long silent ground subsidence hazard culminating in a metropolitan disaster in Maceió, Brazil’, Scientific Reports, 11(1), 7704.

Barbosa, F.L.R., Guimarães, R.F., Carvalho Junior, O.A. and Gomes, R.A.T. (2021) ‘Land Use/Land Cover (LULC) classification based on SAR/Sentinel 1 image in Distrito Federal, Brazil’, Sociedade & Natureza, 33, e55954.
